"""
generate.py
Ties retrieval + generation together: retrieves relevant chunks,
builds a numbered-source prompt, asks the local Ollama model to
answer using only those sources (citing by number), then maps each
[Source N] citation back to real, verified metadata — the model
never has to reproduce a title/arxiv ID itself, which avoids
hallucinated citations.

Usage:
    python src/generate.py "How does self-attention work?"
"""

import sys
import ollama
from retrieval import Retriever

OLLAMA_MODEL = "llama3.1:8b"
TOP_K = 5

SYSTEM_PROMPT = """You are a research assistant that answers questions \
using ONLY the provided sources below. Follow these rules strictly:

1. Only use information found in the provided sources — do not use \
outside knowledge, even if you know the answer.
2. Every claim you make must be followed by a citation marker like \
[Source 1] or [Source 2], referencing which source it came from.
3. If the sources don't contain enough information to answer the \
question, say so plainly instead of guessing.
4. Be concise and direct."""


def build_context_block(chunks: list[dict]) -> str:
    """
    Formats retrieved chunks as numbered sources for the prompt.
    The model only ever sees a number — real metadata (title, page,
    arxiv_id) is attached afterward by us, not generated by the model.
    """
    lines = []
    for i, chunk in enumerate(chunks, start=1):
        lines.append(
            f"[Source {i}] (Paper: {chunk['title']}, Page: {chunk['page_number']})\n"
            f"{chunk['text']}\n"
        )
    return "\n".join(lines)


def build_references(chunks: list[dict]) -> str:
    """Builds the verified reference list from OUR metadata, not the model's output."""
    lines = []
    for i, chunk in enumerate(chunks, start=1):
        authors = chunk["authors"]
        if isinstance(authors, list):
            authors = ", ".join(authors)
        lines.append(
            f"[Source {i}] {chunk['title']} — {authors} "
            f"(p.{chunk['page_number']}, arXiv:{chunk['arxiv_id']})"
        )
    return "\n".join(lines)


def answer_question(query: str, retriever: Retriever, top_k: int = TOP_K):
    chunks = retriever.retrieve(query, top_k=top_k)
    context = build_context_block(chunks)

    user_prompt = f"Sources:\n{context}\n\nQuestion: {query}"

    response = ollama.chat(
        model=OLLAMA_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
    )

    answer = response["message"]["content"]
    references = build_references(chunks)
    return answer, references


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('Usage: python src/generate.py "your question here"')
        sys.exit(1)

    query = sys.argv[1]
    print(f"Question: {query}\n")
    print("Loading retriever (embedding model, Chroma, BM25 index)...")

    retriever = Retriever()

    print("Generating answer...\n")
    answer, references = answer_question(query, retriever)

    print("=== Answer ===")
    print(answer)
    print("\n=== References ===")
    print(references)
